#### Задания на повторение материала

In [3]:
import numpy as np

#### 1

In [157]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### 2

In [12]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [13]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [15]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [17]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### 3

In [25]:
np.reshape(a, (2, -1))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [26]:
np.reshape(a, (3, -1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
np.reshape(a, (4, -1))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [28]:
np.reshape(a, (-1, 2))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [31]:
np.reshape(a, (-1, 1))

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### 5

In [36]:
b = np.random.randn(3, 4)
b

array([[-0.26530157, -0.08209878,  1.10273285,  1.48509496],
       [-0.6068016 , -0.88602888, -1.37321242, -0.48625662],
       [-0.16639987,  1.52221249,  1.93445749,  0.38474063]])

In [47]:
c = a.flatten()
c

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [48]:
c.size == a.size

True

#### 6

In [73]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### 7

In [74]:
b = np.arange(20, 1, -2)

In [78]:
b = np.reshape(b, (1, -1))
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [76]:
b.size == a.size

True

In [77]:
b.shape == a.shape

False

#### 8

In [79]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

In [81]:
v = np.vstack((a, b))
print(v)
v.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

#### 9

In [85]:
a = np.arange(0, 12)

In [86]:
A = a.reshape(4, 3)

In [88]:
At = A.T

In [169]:
B = np.dot(A, At)

In [170]:
B.shape

(4, 4)

In [171]:
# Обратную матрицу найти нельзя так как определитель равен нулю. Матрица - вырожденная.

#### 10

In [172]:
np.random.seed(42)

In [173]:
np.random.randint(0, 10, 3)

array([6, 3, 7])

#### 11

In [174]:
c = np.random.randint(0, 16, 16)

#### 12

In [175]:
c.resize(4, 4)

In [176]:
c = c * 10

In [177]:
D = c + B
D

array([[125,  54,  83, 122],
       [ 34, 110, 186, 222],
       [ 93, 126, 179, 282],
       [102, 142, 262, 342]])

In [178]:
np.linalg.det(D)

-23916799.999999993

In [179]:
np.linalg.matrix_rank(D)

4

In [180]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.01146976, -0.00043819, -0.00342855, -0.00098006],
       [ 0.01503211,  0.04559807,  0.0153666 , -0.04763179],
       [ 0.00637209,  0.01086767, -0.02412697,  0.01056663],
       [-0.01454375, -0.02712737,  0.0131255 ,  0.01489831]])

#### 13

In [181]:
D_inv = D_inv > 0

In [182]:
D_inv

array([[ True, False, False, False],
       [ True,  True,  True, False],
       [ True,  True, False,  True],
       [False, False,  True,  True]])

In [183]:
E = np.where([D_inv], B, c)
E

array([[[  5,  40,  60,  90],
        [ 14,  50,  86, 100],
        [ 23,  86,  30, 212],
        [ 70,  20, 212, 302]]])