#### 1 задание

In [28]:
import numpy as np

In [3]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
a.shape

(5, 2)

In [6]:
np.mean(a, axis = 0)

array([2. , 8.4])

In [7]:
mean_a = np.mean(a, axis = 0)

In [8]:
mean_a

array([2. , 8.4])

#### 2 задание

In [9]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### 3 задание

In [21]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [22]:
a_centered_sp/(5 - 1)

2.0

#### 4 задание

In [27]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])